# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos8"

  config.ssh.insert_key = false # avoid setting up ssh keys as it is just a temporary local vm for testing
  
  config.vm.synced_folder ".", "/vagrant", disabled: true # turn off synced folder

  config.vm.provider :virtualbox do |v|   # set resource limits of VMs
    v.memory = 512
    v.linked_clone = true   # speed up building VMs as it can link to existing VMs to start off.
  end

  # App server 1
  config.vm.define "app1" do |app|
    app.vm.hostname = 'orc-app1.test'
    app.vm.network :private_network, ip: "192.168.60.4"
    app.vm.provision 'centos8-repos-point2vault', type: 'shell', run: 'once' do |sh|
      sh.env = { :PATH => '/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin' }
      sh.inline = <<~'SHELL'
        #!/bin/sh
        find /etc/yum.repos.d -type f -name '*.repo' -exec \
          sed -i -e '/mirrorlist.*/d' -e 's%#baseurl=http://mirror.centos.org%baseurl=http://vault.centos.org%g' {} \;
      SHELL
    end
  end

  # App server 2
  config.vm.define "app2" do |app|
    app.vm.hostname = 'orc-app2.test'
    app.vm.network :private_network, ip: "192.168.60.5"
    app.vm.provision 'centos8-repos-point2vault', type: 'shell', run: 'once' do |sh|
      sh.env = { :PATH => '/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin' }
      sh.inline = <<~'SHELL'
        #!/bin/sh
        find /etc/yum.repos.d -type f -name '*.repo' -exec \
          sed -i -e '/mirrorlist.*/d' -e 's%#baseurl=http://mirror.centos.org%baseurl=http://vault.centos.org%g' {} \;
      SHELL
    end
  end

  # Database server
  config.vm.define "db" do |db|
    db.vm.hostname = 'orc-db.test'
    db.vm.network :private_network, ip: "192.168.60.6"
    db.vm.provision 'centos8-repos-point2vault', type: 'shell', run: 'once' do |sh|
      sh.env = { :PATH => '/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin' }
      sh.inline = <<~'SHELL'
        #!/bin/sh
        find /etc/yum.repos.d -type f -name '*.repo' -exec \
          sed -i -e '/mirrorlist.*/d' -e 's%#baseurl=http://mirror.centos.org%baseurl=http://vault.centos.org%g' {} \;
      SHELL
    end
  end

end
